[package]
name = "oxid8"
version = "0.1.1"
edition = "2021"

[dependencies]
atomic_enum = "0.3.0"
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"
colored = "3.0.0"
cpal = "0.16.0"
random-number = "0.1.9"
ratatui = "0.29.0"
