[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"
colored = "3.0.0"
cpal = "0.16.0"
random-number = "0.1.9"
ratatui = "0.29.0"
